/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.gfnc.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CYKUiModule extends AbstractCYKUiModule {

	public CYKUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
