/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.gfnc;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CYKStandaloneSetup extends CYKStandaloneSetupGenerated {

	public static void doSetup() {
		new CYKStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
