/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.gfnc.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.gfnc.ui.internal.GfncActivator;

public class CYKUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GfncActivator.getInstance().getInjector("org.xtext.example.gfnc.CYK");
	}

}
