/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.gfnc.cYK;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Right</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.gfnc.cYK.CYKPackage#getRight()
 * @model
 * @generated
 */
public interface Right extends Lambda
{
} // Right
