/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.gfnc.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.example.gfnc.services.CYKGrammarAccess;

@SuppressWarnings("all")
public class CYKSyntacticSequencer extends AbstractSyntacticSequencer {

	protected CYKGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Initial_VerticalLineKeyword_4_0_p;
	protected AbstractElementAlias match_Production_VerticalLineKeyword_4_0_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (CYKGrammarAccess) access;
		match_Initial_VerticalLineKeyword_4_0_p = new TokenAlias(true, false, grammarAccess.getInitialAccess().getVerticalLineKeyword_4_0());
		match_Production_VerticalLineKeyword_4_0_p = new TokenAlias(true, false, grammarAccess.getProductionAccess().getVerticalLineKeyword_4_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Initial_VerticalLineKeyword_4_0_p.equals(syntax))
				emit_Initial_VerticalLineKeyword_4_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Production_VerticalLineKeyword_4_0_p.equals(syntax))
				emit_Production_VerticalLineKeyword_4_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     '|'+
	 *
	 * This ambiguous syntax occurs at:
	 *     right+=Lambda (ambiguity) right+=Right
	 *     right+=Right (ambiguity) right+=Right
	 
	 * </pre>
	 */
	protected void emit_Initial_VerticalLineKeyword_4_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     '|'+
	 *
	 * This ambiguous syntax occurs at:
	 *     right+=Right (ambiguity) right+=Right
	 
	 * </pre>
	 */
	protected void emit_Production_VerticalLineKeyword_4_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
