/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.gfnc.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCYKScopeProvider extends DelegatingScopeProvider {
}
