/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.gfnc.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.CYK.ui.internal.CYKActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CYKExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(CYKActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		CYKActivator activator = CYKActivator.getInstance();
		return activator != null ? activator.getInjector(CYKActivator.ORG_XTEXT_EXAMPLE_GFNC_CYK) : null;
	}

}
