/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.gfnc.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.gfnc.CYKRuntimeModule;
import org.xtext.example.gfnc.CYKStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CYKIdeSetup extends CYKStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CYKRuntimeModule(), new CYKIdeModule()));
	}
	
}
