/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.gfnc.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.gfnc.parser.antlr.internal.InternalCYKParser;
import org.xtext.example.gfnc.services.CYKGrammarAccess;

public class CYKParser extends AbstractAntlrParser {

	@Inject
	private CYKGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCYKParser createParser(XtextTokenStream stream) {
		return new InternalCYKParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "GFNC";
	}

	public CYKGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CYKGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
