/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.gfnc.cYK;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.gfnc.cYK.CYKFactory
 * @model kind="package"
 * @generated
 */
public interface CYKPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "cYK";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/gfnc/CYK";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "cYK";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CYKPackage eINSTANCE = org.xtext.example.gfnc.cYK.impl.CYKPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.gfnc.cYK.impl.GFNCImpl <em>GFNC</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.gfnc.cYK.impl.GFNCImpl
   * @see org.xtext.example.gfnc.cYK.impl.CYKPackageImpl#getGFNC()
   * @generated
   */
  int GFNC = 0;

  /**
   * The feature id for the '<em><b>W</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GFNC__W = 0;

  /**
   * The feature id for the '<em><b>Productions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GFNC__PRODUCTIONS = 1;

  /**
   * The number of structural features of the '<em>GFNC</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GFNC_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.gfnc.cYK.impl.ProductionImpl <em>Production</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.gfnc.cYK.impl.ProductionImpl
   * @see org.xtext.example.gfnc.cYK.impl.CYKPackageImpl#getProduction()
   * @generated
   */
  int PRODUCTION = 1;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCTION__LEFT = 0;

  /**
   * The feature id for the '<em><b>Rigth</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCTION__RIGTH = 1;

  /**
   * The number of structural features of the '<em>Production</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.gfnc.cYK.impl.RigthImpl <em>Rigth</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.gfnc.cYK.impl.RigthImpl
   * @see org.xtext.example.gfnc.cYK.impl.CYKPackageImpl#getRigth()
   * @generated
   */
  int RIGTH = 2;

  /**
   * The feature id for the '<em><b>Simple</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIGTH__SIMPLE = 0;

  /**
   * The feature id for the '<em><b>Binary</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIGTH__BINARY = 1;

  /**
   * The feature id for the '<em><b>Lambda</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIGTH__LAMBDA = 2;

  /**
   * The number of structural features of the '<em>Rigth</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIGTH_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.gfnc.cYK.impl.SimpleImpl <em>Simple</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.gfnc.cYK.impl.SimpleImpl
   * @see org.xtext.example.gfnc.cYK.impl.CYKPackageImpl#getSimple()
   * @generated
   */
  int SIMPLE = 3;

  /**
   * The feature id for the '<em><b>Terminals</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE__TERMINALS = 0;

  /**
   * The number of structural features of the '<em>Simple</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.gfnc.cYK.impl.NonTerminalImpl <em>Non Terminal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.gfnc.cYK.impl.NonTerminalImpl
   * @see org.xtext.example.gfnc.cYK.impl.CYKPackageImpl#getNonTerminal()
   * @generated
   */
  int NON_TERMINAL = 4;

  /**
   * The feature id for the '<em><b>No Terminals</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NON_TERMINAL__NO_TERMINALS = 0;

  /**
   * The number of structural features of the '<em>Non Terminal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NON_TERMINAL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.gfnc.cYK.impl.BinaryImpl <em>Binary</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.gfnc.cYK.impl.BinaryImpl
   * @see org.xtext.example.gfnc.cYK.impl.CYKPackageImpl#getBinary()
   * @generated
   */
  int BINARY = 5;

  /**
   * The feature id for the '<em><b>First</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINARY__FIRST = 0;

  /**
   * The feature id for the '<em><b>Second</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINARY__SECOND = 1;

  /**
   * The number of structural features of the '<em>Binary</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINARY_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.gfnc.cYK.GFNC <em>GFNC</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>GFNC</em>'.
   * @see org.xtext.example.gfnc.cYK.GFNC
   * @generated
   */
  EClass getGFNC();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.gfnc.cYK.GFNC#getW <em>W</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>W</em>'.
   * @see org.xtext.example.gfnc.cYK.GFNC#getW()
   * @see #getGFNC()
   * @generated
   */
  EReference getGFNC_W();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.gfnc.cYK.GFNC#getProductions <em>Productions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Productions</em>'.
   * @see org.xtext.example.gfnc.cYK.GFNC#getProductions()
   * @see #getGFNC()
   * @generated
   */
  EReference getGFNC_Productions();

  /**
   * Returns the meta object for class '{@link org.xtext.example.gfnc.cYK.Production <em>Production</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Production</em>'.
   * @see org.xtext.example.gfnc.cYK.Production
   * @generated
   */
  EClass getProduction();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.gfnc.cYK.Production#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.example.gfnc.cYK.Production#getLeft()
   * @see #getProduction()
   * @generated
   */
  EReference getProduction_Left();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.gfnc.cYK.Production#getRigth <em>Rigth</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rigth</em>'.
   * @see org.xtext.example.gfnc.cYK.Production#getRigth()
   * @see #getProduction()
   * @generated
   */
  EReference getProduction_Rigth();

  /**
   * Returns the meta object for class '{@link org.xtext.example.gfnc.cYK.Rigth <em>Rigth</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rigth</em>'.
   * @see org.xtext.example.gfnc.cYK.Rigth
   * @generated
   */
  EClass getRigth();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.gfnc.cYK.Rigth#getSimple <em>Simple</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Simple</em>'.
   * @see org.xtext.example.gfnc.cYK.Rigth#getSimple()
   * @see #getRigth()
   * @generated
   */
  EReference getRigth_Simple();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.gfnc.cYK.Rigth#getBinary <em>Binary</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Binary</em>'.
   * @see org.xtext.example.gfnc.cYK.Rigth#getBinary()
   * @see #getRigth()
   * @generated
   */
  EReference getRigth_Binary();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.gfnc.cYK.Rigth#getLambda <em>Lambda</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Lambda</em>'.
   * @see org.xtext.example.gfnc.cYK.Rigth#getLambda()
   * @see #getRigth()
   * @generated
   */
  EAttribute getRigth_Lambda();

  /**
   * Returns the meta object for class '{@link org.xtext.example.gfnc.cYK.Simple <em>Simple</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simple</em>'.
   * @see org.xtext.example.gfnc.cYK.Simple
   * @generated
   */
  EClass getSimple();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.gfnc.cYK.Simple#getTerminals <em>Terminals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Terminals</em>'.
   * @see org.xtext.example.gfnc.cYK.Simple#getTerminals()
   * @see #getSimple()
   * @generated
   */
  EAttribute getSimple_Terminals();

  /**
   * Returns the meta object for class '{@link org.xtext.example.gfnc.cYK.NonTerminal <em>Non Terminal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Non Terminal</em>'.
   * @see org.xtext.example.gfnc.cYK.NonTerminal
   * @generated
   */
  EClass getNonTerminal();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.gfnc.cYK.NonTerminal#getNoTerminals <em>No Terminals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>No Terminals</em>'.
   * @see org.xtext.example.gfnc.cYK.NonTerminal#getNoTerminals()
   * @see #getNonTerminal()
   * @generated
   */
  EAttribute getNonTerminal_NoTerminals();

  /**
   * Returns the meta object for class '{@link org.xtext.example.gfnc.cYK.Binary <em>Binary</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Binary</em>'.
   * @see org.xtext.example.gfnc.cYK.Binary
   * @generated
   */
  EClass getBinary();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.gfnc.cYK.Binary#getFirst <em>First</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>First</em>'.
   * @see org.xtext.example.gfnc.cYK.Binary#getFirst()
   * @see #getBinary()
   * @generated
   */
  EReference getBinary_First();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.gfnc.cYK.Binary#getSecond <em>Second</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Second</em>'.
   * @see org.xtext.example.gfnc.cYK.Binary#getSecond()
   * @see #getBinary()
   * @generated
   */
  EReference getBinary_Second();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CYKFactory getCYKFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.gfnc.cYK.impl.GFNCImpl <em>GFNC</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.gfnc.cYK.impl.GFNCImpl
     * @see org.xtext.example.gfnc.cYK.impl.CYKPackageImpl#getGFNC()
     * @generated
     */
    EClass GFNC = eINSTANCE.getGFNC();

    /**
     * The meta object literal for the '<em><b>W</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GFNC__W = eINSTANCE.getGFNC_W();

    /**
     * The meta object literal for the '<em><b>Productions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GFNC__PRODUCTIONS = eINSTANCE.getGFNC_Productions();

    /**
     * The meta object literal for the '{@link org.xtext.example.gfnc.cYK.impl.ProductionImpl <em>Production</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.gfnc.cYK.impl.ProductionImpl
     * @see org.xtext.example.gfnc.cYK.impl.CYKPackageImpl#getProduction()
     * @generated
     */
    EClass PRODUCTION = eINSTANCE.getProduction();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRODUCTION__LEFT = eINSTANCE.getProduction_Left();

    /**
     * The meta object literal for the '<em><b>Rigth</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRODUCTION__RIGTH = eINSTANCE.getProduction_Rigth();

    /**
     * The meta object literal for the '{@link org.xtext.example.gfnc.cYK.impl.RigthImpl <em>Rigth</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.gfnc.cYK.impl.RigthImpl
     * @see org.xtext.example.gfnc.cYK.impl.CYKPackageImpl#getRigth()
     * @generated
     */
    EClass RIGTH = eINSTANCE.getRigth();

    /**
     * The meta object literal for the '<em><b>Simple</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RIGTH__SIMPLE = eINSTANCE.getRigth_Simple();

    /**
     * The meta object literal for the '<em><b>Binary</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RIGTH__BINARY = eINSTANCE.getRigth_Binary();

    /**
     * The meta object literal for the '<em><b>Lambda</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RIGTH__LAMBDA = eINSTANCE.getRigth_Lambda();

    /**
     * The meta object literal for the '{@link org.xtext.example.gfnc.cYK.impl.SimpleImpl <em>Simple</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.gfnc.cYK.impl.SimpleImpl
     * @see org.xtext.example.gfnc.cYK.impl.CYKPackageImpl#getSimple()
     * @generated
     */
    EClass SIMPLE = eINSTANCE.getSimple();

    /**
     * The meta object literal for the '<em><b>Terminals</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIMPLE__TERMINALS = eINSTANCE.getSimple_Terminals();

    /**
     * The meta object literal for the '{@link org.xtext.example.gfnc.cYK.impl.NonTerminalImpl <em>Non Terminal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.gfnc.cYK.impl.NonTerminalImpl
     * @see org.xtext.example.gfnc.cYK.impl.CYKPackageImpl#getNonTerminal()
     * @generated
     */
    EClass NON_TERMINAL = eINSTANCE.getNonTerminal();

    /**
     * The meta object literal for the '<em><b>No Terminals</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NON_TERMINAL__NO_TERMINALS = eINSTANCE.getNonTerminal_NoTerminals();

    /**
     * The meta object literal for the '{@link org.xtext.example.gfnc.cYK.impl.BinaryImpl <em>Binary</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.gfnc.cYK.impl.BinaryImpl
     * @see org.xtext.example.gfnc.cYK.impl.CYKPackageImpl#getBinary()
     * @generated
     */
    EClass BINARY = eINSTANCE.getBinary();

    /**
     * The meta object literal for the '<em><b>First</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BINARY__FIRST = eINSTANCE.getBinary_First();

    /**
     * The meta object literal for the '<em><b>Second</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BINARY__SECOND = eINSTANCE.getBinary_Second();

  }

} //CYKPackage
