/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.gfnc.cYK;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>GFNC</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.gfnc.cYK.GFNC#getW <em>W</em>}</li>
 *   <li>{@link org.xtext.example.gfnc.cYK.GFNC#getProductions <em>Productions</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.gfnc.cYK.CYKPackage#getGFNC()
 * @model
 * @generated
 */
public interface GFNC extends EObject
{
  /**
   * Returns the value of the '<em><b>W</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.gfnc.cYK.Terminal}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>W</em>' containment reference list.
   * @see org.xtext.example.gfnc.cYK.CYKPackage#getGFNC_W()
   * @model containment="true"
   * @generated
   */
  EList<Terminal> getW();

  /**
   * Returns the value of the '<em><b>Productions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.gfnc.cYK.Production}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Productions</em>' containment reference list.
   * @see org.xtext.example.gfnc.cYK.CYKPackage#getGFNC_Productions()
   * @model containment="true"
   * @generated
   */
  EList<Production> getProductions();

} // GFNC
