/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.gfnc.cYK;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Non Terminal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.gfnc.cYK.NonTerminal#getNoTerminals <em>No Terminals</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.gfnc.cYK.CYKPackage#getNonTerminal()
 * @model
 * @generated
 */
public interface NonTerminal extends EObject
{
  /**
   * Returns the value of the '<em><b>No Terminals</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>No Terminals</em>' attribute.
   * @see #setNoTerminals(String)
   * @see org.xtext.example.gfnc.cYK.CYKPackage#getNonTerminal_NoTerminals()
   * @model
   * @generated
   */
  String getNoTerminals();

  /**
   * Sets the value of the '{@link org.xtext.example.gfnc.cYK.NonTerminal#getNoTerminals <em>No Terminals</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>No Terminals</em>' attribute.
   * @see #getNoTerminals()
   * @generated
   */
  void setNoTerminals(String value);

} // NonTerminal
