/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.gfnc.cYK;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Right</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.gfnc.cYK.Right#getSimple <em>Simple</em>}</li>
 *   <li>{@link org.xtext.example.gfnc.cYK.Right#getBinary <em>Binary</em>}</li>
 *   <li>{@link org.xtext.example.gfnc.cYK.Right#getLambda <em>Lambda</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.gfnc.cYK.CYKPackage#getRight()
 * @model
 * @generated
 */
public interface Right extends EObject
{
  /**
   * Returns the value of the '<em><b>Simple</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Simple</em>' containment reference.
   * @see #setSimple(Terminal)
   * @see org.xtext.example.gfnc.cYK.CYKPackage#getRight_Simple()
   * @model containment="true"
   * @generated
   */
  Terminal getSimple();

  /**
   * Sets the value of the '{@link org.xtext.example.gfnc.cYK.Right#getSimple <em>Simple</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Simple</em>' containment reference.
   * @see #getSimple()
   * @generated
   */
  void setSimple(Terminal value);

  /**
   * Returns the value of the '<em><b>Binary</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Binary</em>' containment reference.
   * @see #setBinary(Binary)
   * @see org.xtext.example.gfnc.cYK.CYKPackage#getRight_Binary()
   * @model containment="true"
   * @generated
   */
  Binary getBinary();

  /**
   * Sets the value of the '{@link org.xtext.example.gfnc.cYK.Right#getBinary <em>Binary</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Binary</em>' containment reference.
   * @see #getBinary()
   * @generated
   */
  void setBinary(Binary value);

  /**
   * Returns the value of the '<em><b>Lambda</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lambda</em>' attribute.
   * @see #setLambda(String)
   * @see org.xtext.example.gfnc.cYK.CYKPackage#getRight_Lambda()
   * @model
   * @generated
   */
  String getLambda();

  /**
   * Sets the value of the '{@link org.xtext.example.gfnc.cYK.Right#getLambda <em>Lambda</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lambda</em>' attribute.
   * @see #getLambda()
   * @generated
   */
  void setLambda(String value);

} // Right
