/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.gfnc.cYK;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>W</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.gfnc.cYK.W#getLambda <em>Lambda</em>}</li>
 *   <li>{@link org.xtext.example.gfnc.cYK.W#getW <em>W</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.gfnc.cYK.CYKPackage#getW()
 * @model
 * @generated
 */
public interface W extends EObject
{
  /**
   * Returns the value of the '<em><b>Lambda</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lambda</em>' attribute.
   * @see #setLambda(String)
   * @see org.xtext.example.gfnc.cYK.CYKPackage#getW_Lambda()
   * @model
   * @generated
   */
  String getLambda();

  /**
   * Sets the value of the '{@link org.xtext.example.gfnc.cYK.W#getLambda <em>Lambda</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lambda</em>' attribute.
   * @see #getLambda()
   * @generated
   */
  void setLambda(String value);

  /**
   * Returns the value of the '<em><b>W</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.gfnc.cYK.Terminal}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>W</em>' containment reference list.
   * @see org.xtext.example.gfnc.cYK.CYKPackage#getW_W()
   * @model containment="true"
   * @generated
   */
  EList<Terminal> getW();

} // W
